# Aumenta la RAM per il compilatore Kotlin e Compose
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -Dfile.encoding=UTF-8

# Parallelismo e cache di build
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

# Compilazione incrementale
kotlin.incremental=true

# AndroidX senza Jetifier legacy
android.useAndroidX=true
android.enableJetifier=false

kotlin.code.style=official

