package it.unical.ea.enums;

public enum NotificationType {
    PRENOTAZIONE_SUCCESSO,
    NUOVA_PRENOTAZIONE,
    APPROVAZIONE_SOCIETA,
    RIFIUTO_SOCIETA,
    NUOVO_ANNUNCIO,
    RICHIESTA_PARTECIPAZIONE_ITINERARIO,
    ACCETTAZIONE_PARTECIPAZIONE_ITINERARIO,
    RIFIUTO_PARTECIPAZIONE_ITINERARIO
}
