spring.application.name=Travel
spring.devtools.restart.enabled=true

# Configurazione postgres
http://localhost:8080/swagger-ui/index.htmlspring.datasource.url=jdbc:postgresql://localhost:5432/my_project_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
